config/routes.rb
SampleApp::Application.routes.draw do
  
  get "users/new"
  get "/contact", :to => "pages#contact"
  get "/about", :to => "pages#about"
  get "/signin", :to => "pages#signin"
  root "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
#	attr_accessible :name, :email
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :presence => true,
			 :length => {:maximum => 50}
	validates :email,:presence => true,
			 :format => {:with => email_regex},			
			 :uniqueness => {:case_sensitive => false}
	validates :password, :presence =>true,
			     :confirmation => true,
		 	     :length =>{:within => 6..40}
	
	before_save :encrypt_password	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	def User.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
    private
  
	def encrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
	def encrypt(string)
		secure_hash("#{salt}--#{string}")	
	end

end 
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Ruby Tutorials|Home"
  end

  def contact
  @title = "Ruby Tutorials|Contact Us"
  end
  
  def about
  @title = "Ruby Tutorials|About Us "
  end
  
  def signin
  @title = "Ruby Tutorials|Sign in "
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	user.new(user_params)
	
  end
  def user_params
	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class = "round">
	<ul>
					<li> <%= link_to "Column1", "#" %> </li>
					<li> <%= link_to "Column2", "#" %> </li>
					<li> <%= link_to "Column3", "#" %> </li>
					<li> <%= link_to "Column4", "#" %> </li>
				</ul>

 </footer>

app/views/layouts/_header.html.erb
<header>
			<%= image_tag("logo.png", :alt => "Sample App", :class =>"round") %>
			<nav class = "round">
				<ul>
					<li> <%= link_to "Home", root_path %> </li>
					<li> <%= link_to "Contact", contact_path %> </li>
					<li> <%= link_to "About", about_path %> </li>
					<li> <%= link_to "Sign in", signin_path %> </li>
				</ul>
				</nav>
		</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "blueprint/blueprint/screen", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "blueprint/blueprint/print", :media => "print" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <!--[if lt IE 9]>
  <script src= "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]--> 
  <!--[if lt IE 8]>
  <%= stylesheet_link_tag 'blueprint/blueprint/ie' %><![endif] -->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title> <%= @title %> </title>
  <%= csrf_meta_tags %>
  <%=render "layouts/stylesheets" %>
</head>
<body>
	 <div class = "container">
		<%=render "layouts/header" %>
		<section class = "round">	
		<%= yield %>
		</section>
		<%=render "layouts/footer" %>
		</div>
</body>
	

</html>

app/views/pages/about.html.erb
<h1> About page </h1>
<p> 
the About us page

</p>

app/views/pages/contact.html.erb
<h1>Contact us</h1>

<p>contact us </p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>the home page</p>

<%= link_to "SIGN UP NOW!", "#" , :class=> "signup_button round"%>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>